"""empty message

Revision ID: e906601262af
Revises: 
Create Date: 2019-03-02 18:11:31.697480

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_jsonfield


# revision identifiers, used by Alembic.
revision = 'e906601262af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('training_data_url', sa.String(), nullable=False),
    sa.Column('validation_data_url', sa.String(), nullable=True),
    sa.Column('validation_script_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('docker_image_name', sa.String(), nullable=True),
    sa.Column('docker_image_tag', sa.String(), nullable=True),
    sa.Column('docker_image_hash', sa.String(), nullable=True),
    sa.Column('docker_image_size', sa.Integer(), nullable=True),
    sa.Column('test_scores', sqlalchemy_jsonfield.jsonfield.JSONField(), nullable=True),
    sa.Column('final_score', sa.DECIMAL(), nullable=True),
    sa.Column('duration', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation')
    op.drop_table('competition')
    # ### end Alembic commands ###
